import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeModeScript } from "flowbite-react";
import { Toaster } from "react-hot-toast";
import { HiCheck, HiExclamation, HiX } from "react-icons/hi";
import Header from "./components/Header";
import { UserProvider } from "./context/UserContext";
import { cookies } from "next/headers";
import { ThemeInit } from "../.flowbite-react/init";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

async function fetchUserOnServer() {
	const cookieStore = await cookies(); // actually okay here in server code
	const cookieHeader = cookieStore.getAll().map(c => `${c.name}=${c.value}`).join('; ');

	const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/auth/me`, {
		headers: { Cookie: cookieHeader },
		cache: "no-store",
	});

	if (!res.ok) return null;
	return res.json();
}

export default async function RootLayout({
  	children,
}: Readonly<{
  	children: React.ReactNode;
}>) {
	const user = await fetchUserOnServer();

	return (
		<html suppressHydrationWarning>
			<head>
				{/* <ThemeModeScript/> */}
				<ThemeInit />
			</head>
			<body>
				<UserProvider initialUser={user}>
					<Header />
					
					<Toaster 
						position="top-right" 
						reverseOrder={false} 
						toastOptions={{
							// Default options for all toasts
							className: '',
							style: {
								fontSize: '14px',
								borderRadius: '8px',
								padding: '12px 16px',
							},
							// Options for different types
							error: {
								style: {
									background: 'red',
									color: 'white',
								},
								icon: <HiX className="h-5 w-5" />,
							},
							success: {
								style: {
									background: 'green',
									color: 'white',
								},
								icon: <HiCheck className="h-5 w-5" />,
							},
						}}
					/>
					{children}
				</UserProvider>
			</body>
		</html>
	);
}
